coredns/deployment

- systemd/README.md
- systemd/coredns.service
@miekg take a look. I think we should remove that section from main README and instead point people to this repo.
> Move systemd service file from main CoreDNS README

- Makefile
- debian/control
- debian/rules
Can do the same for homebrew and kubernetes - but it requires `jq` to be installed.
> debian: get latest release from github

- kubernetes/coredns.yaml.sed
Pointed out in #13, the label is deprecated.
It is also not present in kube-adm's version of the manifest.
> k8s: remove deprecated label

- kubernetes/coredns.yaml.sed
Pull policy of IfNotPresent makes more sense when pointing to a static version tag.
> kubernetes: fix pull policy 

- kubernetes/coredns.yaml.sed
We should include upstream by default, so externalName services can resolve.
> kubernetes: Add upstream

- kubernetes/coredns.yaml.sed
Add `pods insecure` for feature parity with deprecated behavior of kube-dns.
see: #37
> kubernetes:  add pods insecure

- kubernetes/coredns.yaml.sed
Per-query logging not advisable as a production default.
Metrics dont need to be exposed on the service (becomes meaningless when replicas > 1).
> kubernetes:  no query logging, don't expose metrics at service

- kubernetes/README.md
- kubernetes/coredns.yaml.sed
- kubernetes/deploy.sh
- Add reverse zone fall through to config.
- Move to flag based parameters (the string of all optional parameters was getting clumsy).
> kubernetes: Reverse zone fall through

- kubernetes/README.md
> kubernetes: Fix archaic use of word "middleware"

- kubernetes/coredns.yaml.sed
Scalability woes persist for pod anti-affinity in kubernetes.
See kubernetes/kubernetes#54164 re-opened recently, and kubernetes/kubernetes#57683 reverted by kubernetes/kubernetes#59357.
> kubernetes: remove pod anti affinity

- kubernetes/coredns.yaml.sed
- update docker image to 1.0.6
- remove arg from `upstream`
The CI test will obviously fail until 1.0.6 is released...
> kubernetes: CoreDNS 1.0.6 updates

- kubernetes/coredns.yaml.sed
Adding the `prometheus.io/scrape: "true"` annotation to the service, and listing the metrics port in the deployment enables prometheus to automatically discover and scrape metrics from the coredns endpoints.
> kubernetes: make coredns discoverable by prometheus

- systemd/README.md
- systemd/coredns-sysusers.conf
- systemd/coredns.service
This PR adds the systemd-sysusers specification for the coredns systemd service.
I think that this needs to stay in this repo so that packagers/users can just download the "official" systemd unit along with the user specification.
I'm already using this in the `coredns` and `coredns-bin` aur packages but think that would be useful to have this here with the unit instead of commiting it in the aur package itself.
This is not arch specific but belongs to any distro using systemd.
Signed-off-by: Lorenzo Fontana <lo@linux.com>
> Systemd sysusers directory

- docker/dns.yml
- kubernetes/coredns.yaml.sed
Whether or not coredns/coredns#1767 is done in the container, it should at least be done in orchestration because of separation of concerns.
> Drop unneeded capabilities, make container read-only

- kubernetes/README.md
- kubernetes/rollback.sh
Rollback script to deploy kube-dns in a Kubernetes cluster running CoreDNS
> Rollback to kube-dns

- kubernetes/deploy.sh
Add an option to specify a kubeconfig, in case it is needed to retrieve the kube-dns service IP.
> Add kubeconfig option

- kubernetes/README.md
- kubernetes/coredns.yaml.sed
- kubernetes/deploy.sh
This adds the configmap translation from kube-dns to CoreDNS.
Users can deploy and apply the translation by specifying the `-u` flag.
@chrisohaver @fturib PTAL
> Add kube-dns to CoreDNS configmap translation

- kubernetes/coredns.yaml.sed
move coredns pods from 53 to 10053
redirect service 53 -> 10053
remove net_bind_service capability requirement
> kubernetes: move coredns pods to 10053, and redirect service

- kubernetes/coredns.yaml.sed
bump version to 1.2.2
restore mem limit to prior number, since cache max is smaller by default now in 1.2.2
> k8s: bump to 1.2.2, restore mem limit to 170

- kubernetes/coredns.yaml.sed
Version updated to 1.2.4 and update the deployment to ensure CoreDNS containers binds to linux nodes
> Bump version to 1.2.4 and update deployment

- kubernetes/coredns.yaml.sed
Add port `9153` named `metrics` to the `kube-dns` service. This isn't strictly necessary but is nice to have it aligned with the ports on the Pods. See also: https://github.com/coredns/deployment/pull/80/files
This addresses https://github.com/coreos/prometheus-operator/pull/2149#discussion_r235437007 in the kube-prometheus monitoring configuration.
> Add metrics port 9153 to Service, to match Pod ports

- kubernetes/coredns.yaml.sed
Adding a readinessProbe using the health plugin, which should accurately represent readiness.
This prevents loadbalancing to unready pods, and also allows rolling updates to work as expected.
> Add readinessProbe

- kubernetes/coredns.yaml.sed
Adds `priorityClassName` to give preference in scheduling CoreDNS pods over less critical pods.
> Add priority class

- kubernetes/migration/README.md
- kubernetes/migration/spec.md
This is a draft spec for a migration tool/library that k8s mgmt tools can leverage to migrate CoreDNS Corefiles during upgrades.  Please review and let's discuss.  
Missing anything?
Too ambitious?
How far back should we go?  1.1.3?
> Kubernetes Corefile Migration Tool

- kubernetes/migration/corefile/corefile.go
- kubernetes/migration/corefile/corefile_test.go
- kubernetes/migration/migrate.go
- kubernetes/migration/migrate_test.go
- kubernetes/migration/notice.go
- kubernetes/migration/versions.go
This lays down groundwork for a Corefile migration tool.
Only a few versions defined atm.  Need to fill in for older versions < 1.3.1.
This doesn't implement a CheckCorefile() function as described in the README.
Known issues that i can think of right now:
* Default config detection can be fooled by plugins that allow more than one instance. I think this is minor.
* Comments in corefile get stripped during migration.  I hope we can live with this.  Working around it could be a pita.
> kubernetes: Corefile migration tool groundwork

- kubernetes/coredns.yaml.sed
For a workaround for related issues with crashing due to glog/klog issues, this add an EmptyDir volume and mounts it on /tmp
Fixes #137
> Add /tmp volume mount

- kubernetes/migration/versions.go
Multiple endpoints was "deprecated" in 1.3.1.
"Disabled" in 1.4.0.
Not yet completely removed in 1.5.0.
> Add handler for endpoint deprecation 

- kubernetes/migration/notice.go
- kubernetes/migration/versions.go
In CoreDNS we use 3 phases of deprecation,
1. deprecated - feature announced deprecated, but still fully functional
2. "noop" - feature is removed, but is it still tolerated in the corefile (coredns will still start)
3. removed - feature is removed, and no longer tolerated in the corefile (coredns will not start)
Calling this "noop" status "ignored".
This is mainly just book keeping, but for now an "ignored" feature is considered "removed" when migrating a config.
> Add the noop (ignored) status

- kubernetes/deploy.sh
Using pipefail causes the script to exit when `kubectl` commands cannot find a kubedns configmap.
Its perfectly normal (and more common) to not have a kubedns configmap.
> kubernetes: remove pipefail from setup.sh

- kubernetes/migration/versions.go
Also, adds the `log` plugin to the list of supported plugins.
> Fill in remaining supported CoreDNS versions

- Makefile
- debian/coredns.service
Just build them all, and some typos fixed.
> debian: build all 3 ARCHs

- debian/coredns.manpages
This was missing from the deb.
> debian: add corefile(5) as manual page

- kubernetes/corefile-tool/cmd/migrate.go
The deprecated flag is now optional and its value defaults to false.
> Make deprecated flag in `migrate` optional

- kubernetes/migration/migrate.go
- kubernetes/migration/migrate_test.go
- kubernetes/migration/notice.go
- kubernetes/migration/versions.go
* New to the plugins/options migration structs:
* Adds a new status "newdefault", which indicates when a plugins/option is added to the default configuration for the first time. 
* Adds a new property `add`, which defines how to add the plugin to a server block, or option to its plugin.
* Migrate() now checks for all "newdefault" plugins/options and processes them per the `add` func.
* Defines handlers for `ready` and `loop` plugins.  Plugins placed relative to other plugins.  `ready` is placed in the server blocks containing `kubernetes` plugin.  `loop` is added to server blocks containing `forward` or `proxy`.  As of now in the default config this happens to be the same block.
This is critical for upgraders that always replace the Deployment with the newest version (e.g. kubeadm).  In …
> kubernetes/migration: Add new default plugins/options

- kubernetes/corefile-tool/cmd/released.go
- kubernetes/migration/migrate.go
- kubernetes/migration/versions.go
Easier to extract and verify the release image of CoreDNS by using the docker image SHA than docker Image ID.
> Move from docker image ID to docker image SHA256

- kubernetes/migration/README.md
> k8s migration: use consistent term in README

- kubernetes/migration/go.mod
Required to vendor the migration library in kubernetes/kubernetes.
Error message: 
```
go get github.com/coredns/deployment/kubernetes/migration@master: missing github.com/coredns/deployment/kubernetes/migration/go.mod at revision 517138abe415
```
> Add go.mod

- kubernetes/migration/migrate.go
- kubernetes/migration/migrate_test.go
When upgrading from and to the same version, don't error out anymore, just do a no-op.
E.g.  When Migrating from 1.3.1 to 1.3.1, just leave the corefile as is. When listing deprecation notices from 1.3.1 to 1.3.1, just return an empty list of deprecations instead of an error.
> kubernetes/migration: dont error out on no-op same-verison upgrades

- kubernetes/migration/README.md
- kubernetes/migration/migrate.go
- kubernetes/migration/migrate_test.go
- kubernetes/migration/versions.go
This adds `MigrateDown()`, which handles simple removal of plugins that no longer exist in a destination version when _downgrading_.  e.g. It will remove the `ready` plugin when downgrading from 1.5.0 to any prior version.
`MigrateDown()` won't restore plugins/options that might have been removed in an upward migration. In some cases this could be problematic. e.g. It will not restore `upstream` to the kubernetes plugin when downgrading from a version that no longer requires it a version that does.  This can be added later if needed.
> kubernetes/migration: support simple downgrade cases

- .circleci/config.yml
This PR adds CircleCI to enable the k8s-deployment integration tests from the coredns/ci repo.
> Add circleci for testing k8s-deployment

- kubernetes/migration/migrate.go
- kubernetes/migration/versions.go
This is applicable currently if k8s 1.15 continues to have CoreDNS 1.3.1
> Support multiple k8s version for a release of coredns

- HomebrewFormula/coredns.rb
Is there a way to automate this on new CoreDNS releases?
Maybe adding a Git update to this repo from [`Makefile.release`](https://github.com/coredns/coredns/blob/master/Makefile.release)?
> Update Homebrew formula to 1.6.2

- HomebrewFormula/coredns.rb
Hi, I'm shunirr.  Thank you for useful OSS.
I found 2 problems when uses with Homebrew (macOS). And I fixed it. Please check below.
I tried `brew services` command. But failed.
```
$ sudo brew services start coredns
Error: No such file or directory @ realpath_rec - /usr/local/Cellar/coredns/1.6.2/sbin/coredns
```
I found mistook path `sbin` in `homebrew.mxcl.coredns.plist`. I changed to replace to `bin`.
I tried `coredns` command directory, because I want to check why failed to launch services.
And I saw below messages.
```
$ /usr/local/opt/coredns/bin/coredns --conf /usr/local/etc/coredns/Corefile
/usr/local/etc/coredns/Corefile:5 - Error during parsing: Unknown directive 'proxy'
```
And I refer to https://coredns.io/explugins/forward/ , And I replaced `proxy` to `forward`.
> Fix bugs that failed to launch coredns service with Homebrew (macOS) 

- debian/rules
FTBFS found on Ubuntu Eoan:
```
$ fakeroot debian/rules binary
dh_clean
dh binary --with systemd
dh_update_autotools_config
dh_autoreconf
dh_auto_configure
create-stamp debian/debhelper-build-stamp
dh_testroot
dh_prep
debian/rules override_dh_auto_install
make[1]: Entering directory '/work/vicamo/coredns/deployment'
if [ ! -e coredns_1.6.4_linux_.tgz ]; then curl -L https://github.com/coredns/coredns/releases/download/v1.6.4/coredns_1.6.4_linux_.tgz -o coredns_1.6.4_linux_.tgz; fi
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     12      0 --:--:-- --:--:-- --:--:--    12
if [ ! -e v1.6.4.tar.gz ]; then  curl -L https://github.com/coredns/coredns/archive/v1.6.4.tar.gz -o …
```
> debian: fix DEB_TARGET_ARCH maybe undefined

- kubernetes/deploy.sh
- kubernetes/rollback.sh
Fixes typos on help texts(`-h`) on kubernetes `deploy` and `rollback` convenience scripts
> fix typos on kubernetes deployment scripts

- kubernetes/coredns.yaml.sed
Bumps CoreDNS version to 1.6.5 and adds pod anti-affinity to the deployment.
It also adds the `lameduck` option to the `health` plugin.
Fixes #197  
FIxes #199 
Signed-off-by: Sandeep Rajan <srajan@infoblox.com>
> Update CoreDNS version and update manifest

- kubernetes/coredns.yaml.sed
The K8s Cluster DNS Spec 1.1 removed the requirement to support the deprecated pod ip dns names (e.g. `1-2-3-4.default.pod.cluster.local.`). kubernetes/dns#335
> Update coredns.yaml.sed to match k8s dns spec 1.1

- HomebrewFormula/coredns.rb
It would be great if you could create a GitHub Action in `coredns/coredns` which updates and pushed those two files on every release.
> Bump CoreDNS version to 1.6.9

- kubernetes/coredns.yaml.sed
IIRC, the reason for "required" was because previously there were 2 replicas by default, and "preferred" would cause them both to be scheduled on the same node when building a cluster one node at a time.
But since now there is only one replica by default, we should use "preferred", to avoid the potential problem of under-scaling CoreDNS on a system where not enough nodes are available.
> Use preferredDuringScheduling for Pod Anti Affinity

- kubernetes/Upgrading_CoreDNS.md
The "kubectl log" command has been deprecated and will be removed in a future version
> update "kubectl log" to "kubectl logs"

- kubernetes/coredns.yaml.sed
- kubernetes/deploy.sh
Adds the new `max_concurrent` option to _forward_ to mitigate query spikes that might otherwise cause CoreDNS to OOM.  Setting this to 1000 should cap the memory footprint of concurrent upstream requests to within the ballpark of 2 MBs (thats 2MB in addition to the base CoreDNS footprint + cache). This is just a number I landed on after minimal waffling. My baseless reasoning: It's much higher than the kubedns limit (see below), and 2MB "is pretty small" such that it would keep OOMs in check during a query spike, while 1000 concurrent queries "should be large enough" that (considering that coredns would be scaled) it shouldn't be hitting the limit in normal circumstances.  I'm not married to this number.
We could probably safely set this much much lower. The roughly equivalent feature in …
> Update k8s deployment for 1.7.0

- kubernetes/coredns.yaml.sed
The correct place to add this for testing is as a patch in the coredns/ci, for the purpose of testing until coredns is released with endpointslice support.  Once coredns is released with endpointslice support, it can be added here.
> remove endpointslices for now

- README.md
This URL appears to work well, as discussed in https://github.com/coredns/deployment/issues/240.
> Update helm repo url

- .circleci/config.yml
- kubernetes/coredns.yaml.sed
Bump coredns -> 1.8.3, k8s -> 1.20.2, and kind -> 0.10.0
Also add manual module download in circle ci test (required in go 1.16+).
> Bump coredns -> 1.8.3, k8s -> 1.20.2, and kind -> 0.10.0

- .circleci/config.yml
Fix go.sum rebuild in integration test: use `go mod tidy` instead of `go mod download`.
> Fix go.sum rebuild in test

- .circleci/config.yml
use alternate url for curl download of go
> fix circle-ci failure

- kubernetes/coredns.yaml.sed
preferredDuringSchedulingIgnoredDuringExecution cause single node failure in mostly deployment when increasing node one by one by cluster. In most deployment, when one node running coredns is lost, coredns service is outage at least 5mins.Suggest to use **requiredDuringSchedulingIgnoredDuringExecution** instead to avoid single node failure issue.
> preferred cause single node failure of coredns

- kubernetes/coredns.yaml.sed
> Kubernetes: Bump CoreDNS to 1.9.1

- debian/control
Signed-off-by: Malware Utkonos <utkonos@malwarolo.gy>
The package `dh-systemd` is a transitional package and is not needed in newer releases. It does not exist in debian/bullseye, debian/bookworm, ubuntu/impish, or ubuntu/jammy. The following question on AskUbuntu demonstrates a trick using the version for the package `base-files` to determine the release of Debian or Ubuntu.
https://askubuntu.com/questions/760853/how-can-i-create-a-debian-control-file-that-differs-based-on-ubuntu-release
Here are the versions used to determine that `>= 11.1~` is correct:
| Release | base-files | dh-systemd |
| ------------- | ------------- | ------------- |
| Buster | 10.3+deb10u12 | Yes |
| Focal | 11ubuntu5 | Yes |
| Focal-Updates | 11ubuntu5.5 | Yes |
| Hirsute | 11ubuntu19 | No |
| Bullseye | …
> Package dh-systemd only in old releases. Fixes #269

- debian/control
Signed-off-by: Malware Utkonos <utkonos@malwarolo.gy>
The two fields missing from the general paragraph in the Debian control file were Section and Priority. The Section is set to "net" because this is where all other DNS servers are located in Debian's package repository. The Priority is set to "optional" according to the control file policy documentation.
https://www.debian.org/doc/debian-policy/ch-controlfields.html#source-package-control-files-debian-control
https://www.debian.org/doc/debian-policy/ch-archive.html#s-subsections
https://packages.debian.org/unstable/
https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-priority
https://www.debian.org/doc/debian-policy/ch-archive.html#s-priorities
In addition to the issue that this PR fixes, in Ubuntu 22.04 LTS, a new, …
> Set recommended control fields: Section and Priority. Fixes #256

- kubernetes/coredns.yaml.sed
What this PR does / why we need it:
- Kubernetes recommends [some standard labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/), coreDNS helm chart added them [4 years ago](https://github.com/coredns/helm/commit/34c7cb523ddc6150cd2cca406b583aa13bf5dd5c). 
- Following [coredns chart](https://github.com/coredns/helm/blob/0dbb02cedec3851e19031cde10f63901bbaf64bb/charts/coredns/templates/service.yaml#L16), this deployment should have at least the `app.kubernetes.io/name` one and then we should add it in the kubeadm static manifest
- Related to https://github.com/kubernetes/kubernetes/pull/113433#issuecomment-1297952514
Not sure if we want to update the label selectors due to the upgrade path. In the helm chart, it was updated as well. 
---
Our use-case:
> …
> feat(labels): adding standard labels to k8s deployment and service

- kubernetes/CoreDNS-k8s_version.md
Updating this chart to include the version of CoreDNS installed by kubeadm for Kubernetes 1.25
Signed-off-by: Jay Beale <jay.beale@gmail.com>
> Updating this chart to include Kubernetes 1.25 and CoreDNS 1.9.3

- systemd/README.md
- systemd/coredns-log.conf
- systemd/coredns.service
in systemd configuration:
Added log files (with log rotation)
changed workingdir from ~ to /var/lib/coredns (to some people this causes problems)
> In systemd: added log files and changed workingdir

- kubernetes/CoreDNS-k8s_version.md
As per https://github.com/kubernetes/kubernetes/pull/120116 Kubernetes 1.29 supports CoreDNS v1.11.1
> Add Kubernetes 1.29 and 1.30

- .circleci/config.yml
- image ubuntu-1604:201903-01 is not a valid resource class
https://app.circleci.com/pipelines/github/coredns/deployment/167/workflows/54743828-9787-4b62-813b-192f0ddd9064/jobs/166/release-insights
> bump ubuntu to 2204

- kubernetes/CoreDNS-k8s_version.md
related: https://github.com/coredns/deployment/pull/301
kubeadm v1.32 still uses coredns v1.11.3 same as v1.31.
https://github.com/kubernetes/kubernetes/blob/70d3cc986aa8221cd1dfb1121852688902d3bf53/build/dependencies.yaml#L32-L47
> Add Kubernetes 1.32
