coredns/deployment

kubernetes/README.md

Fixes: issue 7
Files changed:  kubernetes/README.md

[issue/7] fix minor typos in Kubernetes README.md

---

kubernetes/README.md
kubernetes/coredns.yaml.sed

Update k8s manifests to match the ones proposed in the kubeadm PR (kubernetes/kubernetes#52501).
Hard code version to current release for now ...  can modify script to pull latest version later.
Remove references to deleted file in README.

Update k8s manifests

---

HomebrewFormula/coredns.rb
README.md

Fixed bugs in HomeBrew formula and added more info to the readme.

---

kubernetes/README.md
kubernetes/coredns.yaml.sed
kubernetes/deploy.sh

* Add optional pod cidr
* Remove note about CIDRs being multiples of 8 (fixed in 0.9.10)
* Remove unused YAML option

k8s: add pod cidrs option

---

kubernetes/coredns.yaml.sed

kubernetes: bump coredns version

---

kubernetes/deploy.sh

... for cases where the kube-dns service doesn't exist when running the script.

kubernetes: Add optional DNS-IP paramater

---

kubernetes/coredns.yaml.sed

Bump replicas to 2, and add rolling update strategy.

kubernetes: rolling update strategy

---

kubernetes/coredns.yaml.sed

Adding pod anti-affinity to the deployment manifest.

---

kubernetes/coredns.yaml.sed

Removing the master toleration to stop pods being deployed to master nodes

---

kubernetes/coredns.yaml.sed

bump coredns version in k8s

---

kubernetes/coredns.yaml.sed

I merged the last PR on auto-pilot... My original intent was just to test the k8s.gcr.io repo image, but not commit the PR.

kubernetes: Point to our repo

---

kubernetes/coredns.yaml.sed

Add prometheus scrape port

---

kubernetes/coredns.yaml.sed

New version of CoreDNS and add loadbalance plugin.
Signed-off-by: Miek Gieben <miek@miek.nl>

Up version to 1.2.0 in kubernetes

---

kubernetes/README.md

Inserted a paragraph on top of the readme.
I guess will stay for several months.

Call for feedback on CoreDNS adoption

---

kubernetes/coredns.yaml.sed

Also keeps in sync with the k8s manifests

Resync with the k8s manifests

---

kubernetes/coredns.yaml.sed
kubernetes/deploy.sh

kubernetes: bump to 1.2.1, add loop

---

kubernetes/deploy.sh

Solution: quote ${YAML_TEMPLATE} when calling the sed command

---

kubernetes/README.md

I asked to close the Survey.
Removing the mention to that survey.

Removing Survey link

---

kubernetes/Scaling_CoreDNS.md

This is a first shot at a doc that guides users in tuning CoreDNS deployments in K8s.
PTAL
Thanks!

Add a document on Scaling CoreDNS in kubernetes clusters

---

kubernetes/Scaling_CoreDNS.md

Add version info to scale doc

---

kubernetes/coredns.yaml.sed

per kubernetes/kubernetes#70868

remove master toleration

---

kubernetes/coredns.yaml.sed

Switch to apps/v1 API for deployment

---

kubernetes/rollback.sh

It thwarts the existing error check and message.
see also #144

Remove pipefail from rollback.sh

---

kubernetes/migration/migrate.go
kubernetes/migration/migrate_test.go

Replica of #147 branched from a clean master.

Input validation for Version strings

---

kubernetes/migration/migrate_test.go
kubernetes/migration/versions.go

- Adds the options in proxy and forward plugins.
- Handles deprecation case in proxy options.
- Improve and add a unit test.

Add proxy and forward options

---

kubernetes/migration/notice.go

adds string representation of notices of _newdefault_

kubernetes/migration: to string for newdefault

---

HomebrewFormula/coredns.rb

Fixes #133. Seems like the correct way forward per dart-lang/homebrew-dart#58.

Replace MacOS.prefer_64_bit with Hardware::CPU.is_64_bit.

---

kubernetes/migration/migrate.go
kubernetes/migration/migrate_test.go

Include new default plugins in list of deprecation notification returned by "Deprecated()"...

k8s migration: include add notifications in deprecation result

---

kubernetes/migration/README.md
kubernetes/migration/migrate.go
kubernetes/migration/notice.go

k8s migration: Clean up docs

---

kubernetes/corefile-tool/README.md
kubernetes/corefile-tool/cmd/downgrade.go
kubernetes/corefile-tool/cmd/root.go
kubernetes/corefile-tool/cmd/unsupported.go

Adds a command line for `downgrade`.
Usage:
```
corefile-tool downgrade --from 1.5.0 --to 1.4.0 --corefile /path/to/Corefile
```

Add command for downgrade

---

kubernetes/coredns.yaml.sed

Signed-off-by: Sandeep Rajan <srajan@infoblox.com>

Bump CoreDNS to 1.6.6

---

kubernetes/coredns.yaml.sed

- Bumps coredns version to 1.6.7
- Updates beta OS label to GA

Update coredns version and manifest

---

.circleci/config.yml

Updated the ci to fetch the latest Go version.

Fix compile error in circleci

---

kubernetes/coredns.yaml.sed
kubernetes/deploy.sh

Remove support for federation in deploy script

---

kubernetes/Scaling_CoreDNS.md

This fixes the scaling coredns document duplicated word

Fix scaling coredns document

---

kubernetes/coredns.yaml.sed

allow list/watch endpointslice

---

kubernetes/coredns.yaml.sed

Bump to k8s deployment to CoreDNS 1.8.4

---

README.md
debian/rules

Run make with -e so users can override makefile variables

---

kubernetes/README.md

Deprecate K8s deployment scripts per #282

Deprecate K8s deployment scripts
